### ISSUE TITLE
can not download 

### ISSUE THREAD

**Issue by pangyf10** [inbasic/turbo-download-manager#38] opened 2016-03-25 06:18 UTC
http://www.download.hr/download-k-lite-codec-pack-basic.html

I can not download the software from this website by using tdm，but default download manager can.

tdm 0.2.4,firefox x86 46b5,win10 x64

**Comment by inbasic** [comment] 2016-04-30 13:21
This issue is fixed on 0.2.5b3. Try it here; https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/firefox.xpi?raw=true

General note: the issue is fixed on Firefox and Electron versions. Chrome and Android versions still face this issue as it is not possible to set referrer page in these platforms. It is very unlikely that I can find a workaround for these platforms.

Thanks for the report!

**Closed as completed by inbasic** 2016-04-30 13:21 UTC
