### ISSUE TITLE
Option to force use of download manager

### ISSUE THREAD

**Issue by Gibbz** [inbasic/turbo-download-manager#33] opened 2016-02-11 04:13 UTC
Is there an option to force the use of the download manager?
Often (eg source forge) when you get a link to a automatic page it doesn't give you an option to use a download manager. It would be handy to have a way to completely force overwriting the use of the default download manager in firefox....

**Comment by inbasic** [comment] 2016-02-11 07:14
Can you send me the link of a page with this problem. Normally Firefox should have shown you the download dialog and there you can select TDM.

**Comment by Gibbz** [comment] 2016-02-11 09:19
https://sourceforge.net/projects/quelea/files/

just click the latest file in the top center of the screen and wait for the download windows to appear...

**Comment by inbasic** [comment] 2016-02-14 06:21
![screen shot 2016-02-14 at 09 50 12](https://cloud.githubusercontent.com/assets/351062/13032249/66b10668-d300-11e5-9def-1fdf47d4c3d9.png)

I am pretty sure it is related to the server hosting the file. What is the link you get for the direct download?

**Comment by Gibbz** [comment] 2016-02-15 03:16
ah okay...
This is the dialog i get...
![download](https://cloud.githubusercontent.com/assets/650506/13039045/7d71ebac-d3ea-11e5-97c9-e27edfa6a6bf.jpeg)

**Comment by inbasic** [comment] 2016-02-16 08:50
Can you post the direct download link?

**Comment by Gibbz** [comment] 2016-02-17 04:53
Yup, try this one out
http://downloads.sourceforge.net/project/quelea/2016.0/quelea-2016.0-windows-install.exe?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fquelea%2Ffiles%2F&ts=1455684771&use_mirror=jaist

**Comment by inbasic** [comment] 2016-03-13 07:42
Duplicate of https://github.com/inbasic/turbo-download-manager/issues/36; will be fixed on 0.1.5
You can try the dev version right now.

**Closed as completed by inbasic** 2016-03-13 07:42 UTC
