### ISSUE TITLE
Can't found the downloaded file.

### ISSUE THREAD

**Issue by pengweichu** [inbasic/turbo-download-manager#17] opened 2015-11-18 05:18 UTC
I'm installed it with Chrome Version 46.0.2490.86 m, I downloaded the file to my desktop, but usually after the filed download completed, there no any file present on my desktop, not always, sometimes the file is presented.

**Comment by inbasic** [comment] 2015-11-18 06:15
TDM uses Chrome's Temporary directory to store files, when download is complete the extension moves the completed files to your destination folder. 

I am not sure why the file cannot be transferred correctly. I wish there was a case we could regenerate the problem. Anyhow, please click on the _i_ button when download is complete and see if any error is printed in the log window.

This is where you can find the files while they are being downloaded:
`C:\Users\{user}\AppData\Local\Google\Chrome\User Data\Default\File System\`
Note that the name is a set of random characters and there is no extension for files.

**Comment by pengweichu** [comment] 2015-11-18 07:36
Thanks for your comments, I have been replicate it. The log shows as the screenshot.

I also looked it in C:\Users{user}\AppData\Local\Google\Chrome\User Data\Default\File System\, no such file there - my download file is large, in this folder just a few small files.

![1](https://cloud.githubusercontent.com/assets/12697283/11235165/fa751a42-8e09-11e5-85b3-6365d9779a09.png)

**Comment by inbasic** [comment] 2015-11-18 07:40
How about this folder
`C:\Users[myUserName]\AppData\Local\Google\Chrome\User Data\Default\Storage\ext[a long string]\def\File System`

Is this happening only for large files?

**Comment by pengweichu** [comment] 2015-11-18 08:10
Hi, the file is here: C:\Users\myname\AppData\Local\Google\Chrome\User Data\Default\Storage\ext\kemfccojgjoilhfmcblgimbggikekjip\def\File System\primary\t\00\00000000

The 00000000 file size is same to the downloaded file, but usually TDM doesn't copy it to my desktop(I set my desktop as dest folder.

**Comment by inbasic** [comment] 2015-11-18 09:25
So that 00000000 file was fine after changing its name?

I have made a chance that probably fixes the problem. Can you confirm by install this custom build
https://github.com/inbasic/turbo-download-manager/blob/master/builds/packed/chrome.zip?raw=true

Download the zip file and extract it in a folder. Now open chrome://extensions/ and activate the `Developer mode`. Now point the `Load unpacked extension` to the folder. Use this custom build and let me know if the problem is fixed.

**Closed as completed** 2016-01-06 13:26 UTC
